version: '3'

volumes:
   mongodb_volume:
   timescaledb_volume:

services:
  mongodb:
    image: mongo:7.0.0
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
    - 27017:27017
    volumes:
    - mongodb_volume:/data/db
    networks:
    - ifra-network
  
  nats:
      image: nats
      ports:
        - "8222:8222"
        - "4222:4222"
      command: ["--jetstream"]
      networks:
        - ifra-network

  timescaledb:
      image: timescale/timescaledb:latest-pg12
      restart: always
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: timescaledb
        POSTGRES_PASSWORD: password
      volumes:
       - timescaledb_volume:/var/lib/postgresql/data

      networks:
        - ifra-network

networks:
  ifra-network:
    external: true